---

- hosts: all
  pre_tasks:
    - debug:
        var: "{{ item }}"
        verbosity: 0
      with_items:
        - need_sudo
        - zsh_path
        - gem_executable

  roles:
    - { role: system, become: "{{ need_sudo }}", tags: ['system'] }
    - { role: packages-cli, become: "{{ need_sudo }}", tags: ['packages'] }
    - { role: packages-gui, become: "{{ need_sudo }}", tags: ['packages'] }
    - { role: zsh, tags: ['zsh'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: vim, tags: ['vim'] }
    - { role: git, tags: ['git'] }

