---

- name: Update package manager cache for Arch
  pacman:
    update_cache: yes

- name: Install Arch Packages from pacman
  pacman: name={{ item }} state=latest
  with_items:
    - "{{ arch_pacman }}"

- name: Install Arch Packages from AUR
  pacaur: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ arch_aur }}"
    - leiningen
