---

- name: Install packages for git
  package:
    name: "{{ item }}"
    state: latest
  become: "{{ need_sudo }}"
  with_items:
    - tig
    - diff-so-fancy

- name: gitconfig
  copy: src=gitconfig dest={{ ansible_env.HOME }}/.gitconfig backup=yes

- name: gitignore
  copy: src=gitignore_global dest={{ ansible_env.HOME }}/.gitignore_global backup=yes

