---

- name: vimrc
  copy: src=vimrc dest={{ ansible_env.HOME }}/.vimrc backup=yes
  register: vimrc

- name: set up vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest={{ ansible_env.HOME }}/.vim/bundle/Vundle.vim

- name: install plugins
  shell: vim +PluginInstall +qall
  when: vimrc.changed
  async: 60
  poll: 5

