---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: Install Packages For GUI
  package: name={{ item }} state=latest
  with_items:
    - "{{ chromium }}"
    - "{{ vlc }}"
    - "{{ steam }}"
    - "{{ virtualbox }}"
  ignore_errors: yes

- name: Add user to vboxusers groups
  user: 
    name: "{{ ansible_env.USER }}"
    groups: vboxusers
    append: yes
  ignore_errors: yes
  when: ansible_os_family != "Darwin"

