---

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  # when: apache_package_name is not defined or apache_service_name is not defined

- name: Update package manager cache for Arch
  pacman:
    update_cache: yes

- name: Install Packages For Command Line 
  package: name={{ item }} state=latest
  with_items:
    - "{{ vim }}"
    - "{{ tmux }}"
    - "{{ git }}"

