---

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: Update package manager cache for Arch
  pacman:
    update_cache: yes
  when: ansible_os_family == 'Archlinux'

- name: Update package manager cache for Macos
  homebrew:
    update_homebrew: yes
  when: ansible_os_family == 'Darwin'

- name: Install Packages For Command Line 
  package: name={{ item }} state=latest
  with_items:
    - "{{ system_monitor }}"
    - "{{ utils }}"
    - "{{ dev_java }}"

